# Develop override settings

url: https://grtushar.github.io # http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded